# Workflow to build and package up uSync 

name: Build

env:
  BUILD_CONFIG: "Release"

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: 
      - v8/dev 
  pull_request:
    branches: 
      - v8/dev

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest    

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    
    # get nuget
    - name: Setup NuGet.exe for use with actions
      uses: NuGet/setup-nuget@v1.0.2        
    
    # setup msbuild 
    - name: setup-msbuild
      uses: microsoft/setup-msbuild@v1
       
    # restore packages
    - name: nuget restore
      run: nuget restore
    
    # build project 
    - name: Build with MSBuild
      run: msbuild usync8.sln -t:Rebuild -p:Configuration=${{ env.BUILD_CONFIG }} 
