# Workflow to build and package up uSync 

name: Build and Package

env:
  PKG_VERSION: "8.6.2.0"
  BUILD_CONFIG: "PackageOnlyBuild"

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: 
      - v8/dev 
  pull_request:
    branches: 
      - v8/dev

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest    

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    
    # get nuget
    - name: Setup Nuget.exe
      uses: warrenbuckley/Setup-Nuget@v1
    
    # setup msbuild 
    - name: setup-msbuild
      uses: microsoft/setup-msbuild@v1
       
    # restore packages
    - name: nuget restore
      run: nuget restore
    
    # build project 
    - name: Build with MSBuild
      run: msbuild usync8.sln -p:Configuration=${{ env.BUILD_CONFIG }}
    
    # package up the packages. 
    - name: create packages
      run: | 
        nuget pack uSync8.Core\uSync.Core.nuspec -build -version ${{ env.PKG_VERSION }}-build-${{ github.run_number}} -properties "depends=${{ env.PKG_VERSION }}-build-${{ github.run_number}};Configuration=${{ env.BUILD_CONFIG }}" -OutputDirectory .\output
        nuget pack uSync8.BackOffice\uSync.nuspec -build -version ${{ env.PKG_VERSION }}-build-${{ github.run_number}} -properties "depends=${{ env.PKG_VERSION }}-build-${{ github.run_number}};Configuration=${{ env.BUILD_CONFIG }}" -OutputDirectory .\output
        nuget pack uSync8.BackOffice\uSync.BackOffice.Core.nuspec -build -version ${{ env.PKG_VERSION }}-build-${{ github.run_number}} -properties "depends=${{ env.PKG_VERSION }}-build-${{ github.run_number}};Configuration=${{ env.BUILD_CONFIG }}" -OutputDirectory .\output
        nuget pack uSync8.Community.Contrib\uSyn.Community.Contrib.nuspec -build -version ${{ env.PKG_VERSION }}-build-${{ github.run_number}} -properties "depends=${{ env.PKG_VERSION }}-build-${{ github.run_number}};Configuration=${{ env.BUILD_CONFIG }}" -OutputDirectory .\output
        nuget pack uSync8.ContentEdition\uSync.ContentEdition.nuspec -build -version ${{ env.PKG_VERSION }}-build-${{ github.run_number}} -properties "depends=${{ env.PKG_VERSION }}-build-${{ github.run_number}};Configuration=${{ env.BUILD_CONFIG }}" -OutputDirectory .\output
        nuget pack uSync8.ContentEdition\uSync.ContentEdition.Core.nuspec -build -version ${{ env.PKG_VERSION }}-build-${{ github.run_number}} -properties "depends=${{ env.PKG_VERSION }}-build-${{ github.run_number}};Configuration=${{ env.BUILD_CONFIG }}" -OutputDirectory .\output

    - name: Add Github Nuget repo
      run: |
        nuget sources add -name "github" -source "https://nuget.pkg.github.com/kevinjump/index.json"  -username kevinjump -password ${{ secrets.GITHUB_TOKEN }} 
        nuget setApiKey ${{ secrets.GITHUB_TOKEN }} -Source "github"        
    
    - name: Publish to github nuget
      working-directory: .\output
      run: nuget push *.nupkg -source "github"      
